name: Keep Render Alive
on:
  schedule:
    - cron: '*/13 * * * *'  
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: curl -s https://home-quest-lqlp.onrender.com/ping || true